*******************************************************************************
****** dff-standalone_PT schematic pixel  <vs>  dff-standalone_PT layout pixel
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(P_12_HSL130E, p_12_hsl130e) MOS                  2       7*
(inverter schematic pixel, _) Cell                5       0*
(N_12_HSL130E, n_12_hsl130e) MOS                  4       9*
                                             ------  ------
Total                                            11      16

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(N_12_HSL130E, n_12_hsl130e) MOS                  9       9           9       9
(P_12_HSL130E, p_12_hsl130e) MOS                  7       7           7       7
                                             ------  ------      ------  ------
Total                                            16      16          16      16

Schematic and Layout Match
