#!/bin/sh
cdsVncserver :80
sleep 3
cd /home/23247166/Downloads/elec5503-pixel-design
virtuoso -noautostart -mpssession "virtuoso25735" -mpshost "vdi-l-cos-009" -davinciService "DaVinciService_25735_1747735109" -log '/home/23247166/Downloads/elec5503-pixel-design/logs_23247166/logs0/Job9.log'  -licenseLockFileName '/home/23247166/Downloads/elec5503-pixel-design/.tmp_23247166/.vdi-l-cos-009_25735'  -axlChildIdFlag 9 1>/dev/null  2>/dev/null 
exit $?

