#!/bin/sh
cdsVncserver :80
sleep 3
cd /home/23195279/working-dir/elec5503-pixel-design-fanout-sizing
virtuoso -noautostart -mpssession "virtuoso4266" -mpshost "vdi-l-cos-013" -davinciService "DaVinciService_4266_1746448242" -log '/home/23195279/working-dir/elec5503-pixel-design-fanout-sizing/logs_23195279/logs0/Job1.log'  -licenseLockFileName '/home/23195279/working-dir/elec5503-pixel-design-fanout-sizing/.tmp_23195279/.vdi-l-cos-013_4266'  -axlChildIdFlag 1 1>/dev/null  2>/dev/null 
exit $?

